[[language]]
name = "typescript"
auto-format = true
formatter = { command = "pnpm", args = ["exec", "biome", "format", "--stdin-file-path", "file.ts"] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "pnpm", args = ["exec", "biome", "format", "--stdin-file-path", "file.tsx"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "pnpm", args = ["exec", "biome", "format", "--stdin-file-path", "file.js"] }

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "pnpm", args = ["exec", "biome", "format", "--stdin-file-path", "file.jsx"] }
